// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VitalScope.Insfrastructure;

#nullable disable

namespace VitalScope.Insfrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250927090639_AddNotes")]
    partial class AddNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VitalScope.Insfrastructure.Models.PatientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Anamnesis")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<int?>("PregnancyNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("PregnancyWeek")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Patients", "vital");
                });

            modelBuilder.Entity("VitalScope.Insfrastructure.Models.StudyMainInformationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudyMetaInformationId")
                        .HasColumnType("uuid");

                    b.Property<double>("Time")
                        .HasColumnType("double precision");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("StudyMetaInformationId");

                    b.ToTable("StudyMain", "vital");
                });

            modelBuilder.Entity("VitalScope.Insfrastructure.Models.StudyMetaInformationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("Be")
                        .HasColumnType("real");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<float?>("Glu")
                        .HasColumnType("real");

                    b.Property<float?>("Lac")
                        .HasColumnType("real");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<float?>("Ph")
                        .HasColumnType("real");

                    b.Property<int?>("PregnancyWeek")
                        .HasColumnType("integer");

                    b.Property<int?>("Result")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float?>("СarbonDioxide")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("StudyMetas", "vital");
                });

            modelBuilder.Entity("VitalScope.Insfrastructure.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", "vital");
                });

            modelBuilder.Entity("VitalScope.Insfrastructure.Models.UserSettingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ContractionMax")
                        .HasColumnType("double precision");

                    b.Property<double>("ContractionMin")
                        .HasColumnType("double precision");

                    b.Property<double>("HeartRateMax")
                        .HasColumnType("double precision");

                    b.Property<double>("HeartRateMin")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings", "vital");
                });

            modelBuilder.Entity("VitalScope.Insfrastructure.Models.StudyMainInformationEntity", b =>
                {
                    b.HasOne("VitalScope.Insfrastructure.Models.StudyMetaInformationEntity", "StudyMetaInformation")
                        .WithMany("InfoMetas")
                        .HasForeignKey("StudyMetaInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyMetaInformation");
                });

            modelBuilder.Entity("VitalScope.Insfrastructure.Models.StudyMetaInformationEntity", b =>
                {
                    b.HasOne("VitalScope.Insfrastructure.Models.PatientEntity", "Patient")
                        .WithMany("StudyMetaInformations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("VitalScope.Insfrastructure.Models.UserSettingEntity", b =>
                {
                    b.HasOne("VitalScope.Insfrastructure.Models.UserEntity", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("VitalScope.Insfrastructure.Models.UserSettingEntity", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VitalScope.Insfrastructure.Models.PatientEntity", b =>
                {
                    b.Navigation("StudyMetaInformations");
                });

            modelBuilder.Entity("VitalScope.Insfrastructure.Models.StudyMetaInformationEntity", b =>
                {
                    b.Navigation("InfoMetas");
                });

            modelBuilder.Entity("VitalScope.Insfrastructure.Models.UserEntity", b =>
                {
                    b.Navigation("UserSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
